name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Run a multi-line script
        run: |
          chmod +x ./gradlew && ./gradlew build
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: cd ./terraform/ && terraform init
    - name: Terraform Format
      run: cd ./terraform/ && terraform fmt -check
    - name: Terraform Plan
      run: cd ./terraform/ && terraform plan -input=false
    - name: Terraform Apply
      run: cd ./terraform/ && terraform apply -auto-approve -input=false
