name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: jonasxpx/devops/.github/workflows/reusable-java-build.yml@main
    with:
      project-name: 'file-tool'
      java-version: '21'
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
    environment: production
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: cd ./terraform/ && terraform init
    - name: Terraform Format
      run: cd ./terraform/ && terraform fmt -check
    - name: Terraform Plan
      run: cd ./terraform/ && terraform plan -input=false
    - name: Terraform Apply
      run: cd ./terraform/ && terraform apply -auto-approve -input=false
